export const countryGroupJson = {
  ais: {
    BHR: "Bahrain",
    COM: "Comoros",
    CPV: "Cabo Verde",
    GNB: "Guinea-Bissau",
    MDV: "Maldives",
    MUS: "Mauritius",
    SGP: "Singapore",
    STP: "Sao Tome and Principe",
    SYC: "Seychelles",
  },
  caribbean: {
    AIA: "Anguilla",
    ABW: "Aruba",
    ATG: "Antigua and Barbuda",
    BHS: "Bahamas",
    BLZ: "Belize",
    BMU: "Bermuda",
    BRB: "Barbados",
    CYM: "Cayman Islands",
    DMA: "Dominica",
    DOM: "Dominican Republic",
    KNA: "Saint Kitts and Nevis",
    LCA: "Saint Lucia",
    SXM: "Sint Maarten",
    CUB: "Cuba",
    CUW: "Curaçao",
    JAM: "Jamaica",
    GRD: "Grenada",
    GUY: "Guyana",
    HTI: "Haiti",
    MSR: "Montserrat",
    SUR: "Suriname",
    TCA: "Turks and Caicos Islands",
    TTO: "Trinidad and Tobago",
    VCT: "Saint Vincent and the Grenadines",
    VGB: "Virgin Islands, British",
  },
  pacific: {
    COK: "Cook Islands",
    FJI: "Fiji",
    FSM: "Micronesia, Federated States of",
    KIR: "Kiribati",
    MHL: "Marshall Islands",
    NIU: "Niue",
    NRU: "Nauru",
    PLW: "Palau",
    PNG: "Papua New Guinea",
    SLB: "Solomon Islands",
    TKL: "Tokelau",
    TLS: "Timor-Leste",
    TON: "Tonga",
    TUV: "Tuvalu",
    VUT: "Vanuatu",
    WSM: "Samoa",
  },
};
export const countryColors = ['#DDA63A', '#4C9F38', '#C5192D', '#FF3A21', '#26BDE2', '#FCC30B', '#A21942', '#FD6925', '#DD1367', '#FD9D24', '#8F8B2E', '#3F7E44', '#0A97D9', '#56C02B', '#00689D', '#19486A', '#E5243B']
